include:
  - infra.yaml
  - mysql.yaml
services:
  web:
    build: app
    ports:
      - "8000:5000"
    # depends_on:
    #   - mysql
    networks:
      - mysqlnetwork
      - redisnetwork
    develop:
      watch:
        - action: sync
          path: ./app
          target: /code

# volumes:
#   mysql:
#     driver: local
networks:
  mysqlnetwork:
    driver: bridge
  redisnetwork:
    driver: bridge